# fly.toml app configuration file generated for artio on 2024-05-25T19:43:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'artio'
primary_region = 'mad'

[build]
[build.args]
VITE_API_BASE_URL = 'https://artio.fly.dev/api'
VITE_GOOGLE_API_KEY = ''

[env]
CORS_ORIGIN = 'https://artio.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
